/** Pruebas del cuestionario familiar y del contrato multipart de sus soportes. */
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';

const html = fs.readFileSync('src/templates/familia.html','utf8')
    .replace(/\{%[\s\S]*?%\}/g,'').replace(/\{\{[\s\S]*?\}\}/g,'');
const dom = new JSDOM(html, {runScripts:'outside-only', url:'http://localhost/app/familia'});
const w = dom.window;
await new Promise(resolve => w.addEventListener('load',resolve));
const alerts = [];
w.alert = texto => alerts.push(texto);
w.scrollTo = () => {};
w.confirm = () => true;
w.fetch = async () => ({ok:true,json:async()=>[]});
w.eval(fs.readFileSync('src/static/js/familia.js','utf8'));
w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
const set = (id,value) => { w.document.getElementById(id).value = value; };
const named = (name,value) => { w.document.querySelector(`[name="${name}"]`).value = value; };
const scenarios = () => w.document.querySelectorAll('[data-escenario]');
assert.equal(scenarios().length,3);
set('numero_clases','3'); w.cambiarClases();
assert.equal(scenarios().length,7);
assert.ok(w.validarEscenarios(), 'El reparto de tercios debe sumar 100');
set('numero_clases','2'); w.cambiarClases();
named('acc1_nombre','Persona Prueba'); named('acc1_id_num','12345');
named('acc1_domicilio','Medellín'); named('acc1_porcentaje','100');
assert.equal(w.validateStep(2),false);
assert.match(alerts.at(-1), /parentesco/);
set('acc1_parentesco','Fundador');
assert.equal(w.validateStep(2),true,alerts.at(-1));
const pct = w.document.querySelector('[data-escenario="A+B"] input');
pct.value = '40'; pct.dispatchEvent(new w.Event('input'));
w.showStep(2); w.nextStep(2);
assert.equal(w.document.getElementById('step2').classList.contains('hidden'),false);
assert.match(alerts.at(-1), /100/);
pct.value = '50'; pct.dispatchEvent(new w.Event('input'));
assert.equal(w.validateStep(2),true);
console.log('OK clases: 2 → 3 escenarios; 3 → 7; sumas y parentesco bloquean el avance');

set('nombre_sas','FAMILIA PRUEBA S.A.S.'); w.onRazonSocialInput(); w.marcarConsultaRues();
w.document.querySelector('[name="homonimia"][value="min"]').checked = true;
set('direccion','Carrera 1 # 2-3'); set('barrio','Centro');
set('email','prueba@example.com'); set('telefono1','3001234567');
set('rl_principal_nombre','Persona Prueba'); set('rl_principal_cedula','12345');
set('capital_autorizado','100000000'); set('capital_suscrito','10000000'); set('valor_nominal','1000');
let payload = w.collectAllData();
assert.equal(payload.modulo,'familia'); assert.equal(payload.ciiu_code,'7010');
assert.equal(payload.clases[0].votos_por_accion,10);
assert.equal(payload.escenarios['A+B'].A,50);
assert.equal(payload.elecciones.grupo_familiar,'amplio');
assert.equal(payload.elecciones.limite_rl_pct,20);
assert.equal(payload.opciones.preferencia_suscripcion,true);
assert.equal(payload.accionistas[0].doc_key,'acc1');
assert.equal(payload.accionistas[0].clase,'A');
assert.equal(payload.accionistas[0].parentesco,'Fundador');
assert.equal(payload.rl_principales[0].doc_key,'rl_principal');
assert.ok(!('disposiciones' in payload)); assert.ok(!('modelo_propio' in payload));
for (const campo of ['zona','tipo_local','tenencia','regimen','ingresos_mensuales','responsabilidades_adicionales']) assert.ok(campo in payload,campo);
assert.equal(w.document.getElementById('objeto_social').readOnly,true);
assert.equal(w.document.getElementById('ciiu_search').readOnly,true);
set('grupo_familiar','personalizado'); assert.equal(w.validateStep(6),false);
set('grupo_personalizado','Los fundadores y sus descendientes'); assert.equal(w.validateStep(6),true);
set('grupo_familiar','amplio');
set('numero_clases','1'); w.cambiarClases(); assert.equal(w.collectAllData().opciones.conversion_por_transferencia,false);
set('numero_clases','2'); w.cambiarClases();
w.buildSummary();
assert.match(w.document.getElementById('summary-content').textContent,/Dividendos A\+B/);
console.log('OK contrato familiar, campos de anexos, elecciones, opciones y resumen');

const file = new w.File(['documento de prueba'],'cedula.pdf',{type:'application/pdf'});
const input = w.document.querySelector('#acc_1 input[type="file"]');
Object.defineProperty(input,'files',{configurable:true,value:[file]});
w.fetch = async (url,opts) => {
    assert.equal(url,'/api/extract/cedula'); assert.ok(opts.body instanceof w.FormData);
    return {ok:true,json:async()=>({nombre_completo:'Persona Prueba',numero_documento:'12345',tipo_documento:'CC'})};
};
await w.extractFromCedula(input,'acc1',1);
let enviado;
w.URL.createObjectURL = () => 'blob:prueba'; w.URL.revokeObjectURL = () => {};
w.HTMLAnchorElement.prototype.click = () => {};
w.fetch = async (url,opts) => {
    enviado = {url,...opts};
    return {ok:true,blob:async()=>new w.Blob(['ZIP']),json:async()=>({})};
};
await w.generateDocuments();
assert.equal(enviado?.url,'/api/generate',alerts.at(-1));
assert.ok(enviado.body instanceof w.FormData);
payload = JSON.parse(enviado.body.get('payload'));
assert.equal(payload.modulo,'familia');
assert.equal(enviado.body.get('cedula:acc1').name,'cedula.pdf');
await w.enviarAsistenciaQuarta();
assert.equal(enviado.url,'/api/enviar-asistencia');
assert.ok(enviado.body.get('zip'));
console.log('OK extracción, generación multipart con payload y soportes, asistencia con el último ZIP');
dom.window.close();
console.log('OK test_familia_frontend');
